version: '3.8'
services:
  #La base de datos ya está levantada
  #mysqldb:
  #    image: mysql:5.7
  #    restart: unless-stopped
  #    env_file: ./.env
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #      - MYSQL_DATABASE=$MYSQLDB_DATABASE
  #    ports:
  #      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  #    volumes:
  #      - db:/var/lib/mysql
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  db:
  #– mysqldb:
#
#image: official Docker image
#restart: configure the restart policy
#env_file: specify our .env path that we will create later
#environment: provide setting using environment variables
#ports: specify ports will be used
#volumes: map volume folders
#– app:
#
#depends_on: dependency order, mysqldb is started before app
#build: configuration options that are applied at build time that we defined in the Dockerfile with relative path
#environment: environmental variables that Node application uses
#stdin_open and tty: keep open the terminal after building container